#!/bin/bash

#
# This script must be put in the root android sources.
#

export USE_CCACHE=1
export CCACHE_DIR=~/.ccache/omni-meizu

if [ ! -d "$CCACHE_DIR" ]; then
    mkdir "$CCACHE_DIR"
fi

# Set ccache 10GB
./prebuilts/misc/linux-x86/ccache/ccache -M 10G

# Compiling
. build/envsetup.sh
breakfast m3s
make -j5 recoveryimage
